name: Release to CurseForge and GitHub

on:
  push:
    tags:
      - 'v*.*.*' # Trigger on tags like v1.0.0

jobs:
  release:
    name: Package and Release
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required by BigWigsMods/packager to create GitHub releases

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0 # Fetches all history for all tags and branches to generate changelogs
          persist-credentials: true # Needed by BigWigsMods/packager to create GitHub releases

      - name: Package and Upload to CurseForge and GitHub Releases
        uses: BigWigsMods/packager@16bee9f167d4a445da57aeabcbbc875848e3468a # v2.4.2
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_API_KEY }}
          GITHUB_TOKEN: ${{ github.token }}
        with:
          args: -p "997656"